### ISSUE TITLE
Marca do site não é redimensionada corretamente em celulares

### ISSUE THREAD

**Issue by thicolares** [salvadordevopsdays/salvadordevopsdays.github.io#1]
Basta experimentar em um celular, verá que a marca inicial fica pequena e alinhada à esquerda

**Comment by somatorio** [comment]
Será resolvido no próximo commit :)

**Comment by somatorio** [comment]
Dentro dos meus testes foi resolvido... @colares pode confirmar pra mim?

**Comment by thicolares** [comment]
O que reportei foi resolvido, mas acho que a marca poderia ficar alinhada verticalmente no centro. Não sei se é por causa do header. O que acha?

Se eu conseguir parar, posso eu mesmo resolver também

![image](https://user-images.githubusercontent.com/849493/29921695-fe0f7c26-8e28-11e7-8c9a-26c86dcf64a1.png)

**Comment by somatorio** [comment]
cara eu usei o inkscape (usei a função de alinhamento) e a emulação do chrome pra ver o meio da imagem e da tela, e parece estar bem centralizado
![sem titulo](https://user-images.githubusercontent.com/7087238/29922228-17c45f36-8e2b-11e7-9802-b4c83a12fa99.png)

mas igual vou dar uma olhada

edit: não tinha visto que era centralização vertical... vou ver aqui

**Comment by somatorio** [comment]
Acredito que resolvi @colares :)
pode dar uma olhada?
